GrupoNRJ.Cliente.GestionCafe/GrupoNRJ.Cliente.GestionCafe/Controllers/PlanificacionController.cs
// <copyright file="PlanificacionController.cs" company="GrupoAnalisis">
// Copyright (c) GrupoAnalisis. All rights reserved.
// </copyright>

namespace GrupoNRJ.Cliente.GestionCafe.Controllers
{
    using GrupoNRJ.Cliente.GestionCafe.Utilidades;
    using GrupoNRJ.Modelos.GestionCafe;
    using GrupoNRJ.Modelos.GestionCafe.Respuestas;
    using GrupoNRJ.Modelos.GestionCafe.Solicitudes;
    using Microsoft.AspNetCore.Mvc;

    public class PlanificacionController : Controller
    {
        private readonly ClienteAPI clienteApi;

#pragma warning disable IDE0290 // Usar constructor principal
        public PlanificacionController(ClienteAPI clienteAPI)
#pragma warning restore IDE0290 // Usar constructor principal
        {
            this.clienteApi = clienteAPI;
        }

        public async Task<IActionResult> PlanificacionLotes()
        {
            var listadoProductos = await this.clienteApi.GetAsync<RespuestaBase<List<ObtenerPlanificacionRespuesta>>>("Planificacion/planificacion");
            this.ViewData["planificacion"] = listadoProductos?.Datos ?? new();
            var listadoEstados = await this.clienteApi.GetAsync<RespuestaBase<List<CatalogoRespuesta>>>("Catalogo/obtenerEstado");
            this.ViewData["estados"] = listadoEstados?.Datos ?? new();
            var listadoLotes = await this.clienteApi.GetAsync<RespuestaBase<List<CatalogoRespuesta>>>("Catalogo/obtenerLote");
            this.ViewData["lotes"] = listadoLotes?.Datos ?? new();
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarPlanificacion([FromBody] PlanificacionSolicitud solicitud)
        {
            // Aquí llamamos a un procedimiento almacenado
            var mensaje = new { todoCorrecto = false };
            try
            {
                var respuestaProducto = await this.clienteApi.PostAsync<PlanificacionSolicitud, RespuestaBase<List<ObtenerPlanificacionRespuesta>>>("Planificacion/nueva", solicitud);
                if (respuestaProducto != null)
                {
                    mensaje = new { todoCorrecto = respuestaProducto.Codigo == 0 };
                }
            }
            catch (Exception)
            {
                mensaje = new { todoCorrecto = false };
            }

            return this.Json(mensaje);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InformacionPlanificacion([FromBody] ObtenerPlanificacionLoteSolicitud solicitud)
        {
            // Aquí llamamos a un procedimiento almacenado
            var mensaje = new { Listado = new ObtenerPlanificacionRespuesta() };
            try
            {
                var respuestaProducto = await this.clienteApi.PostAsync<ObtenerPlanificacionLoteSolicitud, RespuestaBase<List<ObtenerPlanificacionRespuesta>>>("Planificacion/planificacion/id", solicitud);
                if (respuestaProducto != null)
                {
                    mensaje = new { Listado = respuestaProducto.Datos[0] ?? new ObtenerPlanificacionRespuesta() };
                }
            }
            catch (Exception)
            {
                mensaje = new { Listado = new ObtenerPlanificacionRespuesta() };
            }

            return this.Json(mensaje);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ModificarPlanificacion([FromBody] PlanificacionSolicitud solicitud)
        {
            // Aquí llamamos a un procedimiento almacenado
            var mensaje = new { todoCorrecto = false };
            try
            {
                var respuestaProducto = await this.clienteApi.PostAsync<PlanificacionSolicitud, RespuestaBase<List<ObtenerPlanificacionRespuesta>>>("Planificacion/actualizar", solicitud);
                if (respuestaProducto != null)
                {
                    mensaje = new { todoCorrecto = respuestaProducto.Codigo == 0 };
                }
            }
            catch (Exception)
            {
                mensaje = new { todoCorrecto = false };
            }

            return this.Json(mensaje);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearLote([FromBody] AgregarLoteSolicitud solicitud)
        {
            // Aquí llamamos a un procedimiento almacenado
            var mensaje = new { todoCorrecto = false };
            try
            {
                var respuestaProducto = await this.clienteApi.PostAsync<AgregarLoteSolicitud, RespuestaBase<bool>>("Planificacion/CrearLote", solicitud);
                if (respuestaProducto != null)
                {
                    mensaje = new { todoCorrecto = respuestaProducto.Datos };
                }
            }
            catch (Exception)
            {
                mensaje = new { todoCorrecto = false };
            }

            return this.Json(mensaje);
        }
    }
}

GrupoNRJ.Cliente.GestionCafe/GrupoNRJ.Cliente.GestionCafe/Views/Planificacion/PlanificacionLotes.cshtml
@using GrupoNRJ.Modelos.GestionCafe
@using GrupoNRJ.Modelos.GestionCafe.Respuestas
@{
    Layout = "_Layout";
    List<ObtenerPlanificacionRespuesta> planificacionLotes = this.ViewData["planificacion"] as List<ObtenerPlanificacionRespuesta>;
    List<CatalogoRespuesta> estados = this.ViewData["estados"] as List<CatalogoRespuesta> ?? new();
    List<CatalogoRespuesta> lotes = this.ViewData["lotes"] as List<CatalogoRespuesta> ?? new();
}

@Html.AntiForgeryToken()

<!-- Título + Botón en la misma línea -->
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class="mb-0">Inventario de café</h2>

    <!-- Contenedor para los botones a la derecha -->
    <div class="d-flex gap-2">
        <!-- Botón Agregar -->
        <button class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#modalAgregar">
            <i class="bi bi-plus-lg"></i> Agregar Planificacion
        </button>
        <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalAgregarLote">
            <i class="bi bi-plus-lg"></i> Agregar Lote
        </button>
    </div>
</div>
@if (planificacionLotes != null)
{
    <hr />
    <table id="tablaPlanificacion" class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th>Planificacion</th>
                <th>Lote</th>
                <th>Estado</th>
                <th>Inicio</th>
                <th>Fin</th>
                <th style="width: 40px;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ObtenerPlanificacionRespuesta item in planificacionLotes)
            {
                <tr>
                    <td>Plan. #@item.IdPlanificacion</td>
                    <td>Lote #@item.IdLote</td>
                    <td>@item.Estado</td>
                    <td>@item.FechaInicio</td>
                    <td>@item.FechaFin</td>
                    <td class="d-flex gap-2">
                        <!-- Botón de editar -->
                        <button type="button" attr-valor="@item.IdPlanificacion" class="modificarProducto btn btn-sm btn-outline-secondary flex-fill" title="Editar">
                            <i class="bi bi-pencil"></i>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<!-- Modal Agregar -->
<div class="modal fade" id="modalAgregar" tabindex="-1" aria-labelledby="modalAgregarLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Encabezado -->
            <div class="modal-header">
                <h5 class="modal-title" id="modalAgregarLabel">Agregar Producto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <!-- Cuerpo con formulario -->
            <div class="modal-body">
                <form id="formAgregar">
                    <div class="mb-3">
                        <label for="inicio" class="form-label">Inicio</label>
                        <input type="date" id="inicio" class="form-control" placeholder="Escribe el nombre" required>
                    </div>
                    <div class="mb-3">
                        <label for="fin" class="form-label">Fin</label>
                        <input type="date" id="fin" class="form-control" placeholder="ingrese la cantidad" required>
                    </div>

                    <div class="mb-3">
                        <label for="estado" class="form-label">Estados: </label>
                        <select id="estado" class="form-control" required>
                            @foreach (CatalogoRespuesta item in estados)
                            {
                                <option value="@item.IdCatalogo">@item.Nombre</option>
                            }
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="lotes" class="form-label">Lotes: </label>
                        <select id="lotes" class="form-control" required>
                            @foreach (CatalogoRespuesta item in lotes)
                            {
                                <option value="@item.IdCatalogo">@item.Nombre</option>
                            }
                        </select>
                    </div>
                </form>
            </div>

            <!-- Footer con botones -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success" id="btnGuardar">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Modificar -->
<div class="modal fade" id="modalModificar" tabindex="-1" aria-labelledby="modalModificarLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Encabezado -->
            <div class="modal-header">
                <h5 class="modal-title" id="modalModificarLabel">Modificar Producto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <!-- Cuerpo con formulario -->
            <div class="modal-body">
                <form id="formModificar">
                    <div class="mb-3">
                        <label for="inicioM" class="form-label">Inicio</label>
                        <input type="date" id="inicioM" class="form-control" placeholder="Escribe el nombre" required>
                    </div>
                    <div class="mb-3">
                        <label for="finM" class="form-label">Fin</label>
                        <input type="date" id="finM" class="form-control" placeholder="ingrese la cantidad" required>
                    </div>

                    <div class="mb-3">
                        <label for="estadoM" class="form-label">Estados: </label>
                        <select id="estadoM" class="form-control" required>
                            @foreach (CatalogoRespuesta item in estados)
                            {
                                <option value="@item.IdCatalogo">@item.Nombre</option>
                            }
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="lotesM" class="form-label">Lotes: </label>
                        <select id="lotesM" class="form-control" required>
                            @foreach (CatalogoRespuesta item in lotes)
                            {
                                <option value="@item.IdCatalogo">@item.Nombre</option>
                            }
                        </select>
                        <a href="@Url.Action("Lotes","Planificacion")">Agregar nuevo lote</a>
                    </div>
                </form>
            </div>
            <!-- Footer con botones -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success" id="btnModificar">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Agregar Lote -->
<div class="modal fade" id="modalAgregarLote" tabindex="-1" aria-labelledby="modalAgregarLabelLote" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Encabezado -->
            <div class="modal-header">
                <h5 class="modal-title" id="modalAgregarLabelLote">Agregar Producto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            <!-- Cuerpo con formulario -->
            <div class="modal-body">
                <form id="formLote">
                    <div class="mb-3">
                        <label for="cantidadL" class="form-label">Cantidad</label>
                        <input type="number" id="cantidadL" class="form-control" placeholder="Escribe el nombre" required>
                    </div>
                    <div class="mb-3">
                        <label for="granosL" class="form-label">Granos: </label>
                        <select id="granosL" class="form-control" required>
                            <option value="arabica">Arabica</option>
                            <option value="robusta">Robusta</option>
                            <option value="blends">Blends</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="tuesteL" class="form-label">Tueste: </label>
                        <select id="tuesteL" class="form-control" required>
                            <option value="claro">Claro</option>
                            <option value="medio">Medio</option>
                            <option value="oscuro">Oscuro</option>
                        </select>
                    </div>
                </form>
            </div>

            <!-- Footer con botones -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success" id="btnGuardarL">Guardar</button>
            </div>
        </div>
    </div>
</div>


<script>
    var urlCrearPlanificacion = '@Url.Action("AgregarPlanificacion")';
    var urlObtenerPlanificacion = '@Url.Action("InformacionPlanificacion")';
    var urlModificarPlanificacion = '@Url.Action("ModificarPlanificacion")';
    var urlCrearLote = '@Url.Action("CrearLote")';
</script>

<script defer src="~/js/PlanificacionLotes.js"></script>